backend:
  name: github
  repo: ARogala/yank-and-brit-art

media_folder: src/img/uploads
public_folder: img/uploads
publish_mode: editorial_workflow

display_url: https://yankandbritart.netlify.com

collections:
  - name: AcrylicPaintings
    label: AcrylicPaintings
    folder: src/blog/AcrylicPaintings
    create: true
    fields:
      - { name: path, label: Path, default: src/blog/AcrylicPaintings/ }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Author, widget: string }
      - { name: category, label: Category, widget: string }
      - { name: subCategory, label: SubCategory, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: DIY
    label: DIY
    folder: src/blog/DIY
    create: true
    fields:
      - { name: path, label: Path, default: src/blog/DIY/ }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Author, widget: string }
      - { name: category, label: Category, widget: string }
      - { name: subCategory, label: SubCategory, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: About Me
    label: About Me
    folder: src/markdown/about
    create: false
    fields:
      - { name: path, label: Path, default: src/markdown/about/ }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Author, widget: string }
      - { name: body, label: Body, widget: markdown }
  - name: Home
    label: Home
    folder: src/markdown/index
    create: false
    fields:
      - { name: path, label: Path, default: src/markdown/index/ }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Author, widget: string }
      - { name: body, label: Body, widget: markdown }